### ISSUE TITLE
RxSwift 学习

### ISSUE THREAD

**Issue by futantan** [futantan/oldBlog#2]
## 学习RxSwift

- 读完 [Document](https://github.com/ReactiveX/RxSwift/tree/master/Documentation)

## TODOs

- [x] [Why](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Why.md)
- [x] [GettingStarted](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md)
- [ ] [ComparisonWithOtherLibraries](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/ComparisonWithOtherLibraries.md)
- [ ] [DesignRationale](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/DesignRationale.md)
- [ ] [ExampleApp](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/ExampleApp.md)
- [ ] [Examples](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Examples.md)
- [ ] [GettingStarted](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/GettingStarted.md)
- [ ] [HotAndColdObservables](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/HotAndColdObservables.md)
- [ ] [Linux](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Linux.md)
- [ ] [MathBehindRx](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/MathBehindRx.md)
- [ ] [Migration](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Migration.md)
- [ ] [Playgrounds](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Playgrounds.md)
- [ ] [Schedulers](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Schedulers.md)
- [ ] [Subjects](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Subjects.md)
- [ ] [Schedulers](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Schedulers.md)
- [ ] [UnitTests](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/UnitTests.md)
- [ ] [Tips](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Tips.md)
- [ ] [Tips](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Tips.md)
- [ ] [Units](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Units.md)
- [ ] [Tips](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Tips.md)
- [ ] [Warnings](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Warnings.md)
