### ISSUE TITLE
JavaScript Meta Programming

### ISSUE THREAD

**Issue by futantan** [futantan/oldBlog#31]
- [ ] https://www.keithcirkel.co.uk/metaprogramming-in-es6-symbols/
- [ ] https://github.com/getify/You-Dont-Know-JS/blob/master/es6%20&%20beyond/ch7.md
- [ ] http://es6.ruanyifeng.com/#docs/symbol
- [ ] https://book.douban.com/review/8554346/
- [ ] http://www.dzautner.com/meta-programming-javascript-using-proxies/
- [ ] http://www.cnblogs.com/liuyanlong/archive/2013/05/27/3102161.html
- [ ] https://zhuanlan.zhihu.com/p/20754002
