### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by futantan** [futantan/oldBlog#37]
## FP
📚Books
- [x] [Functional-Light-JS](https://github.com/getify/functional-light-js)
- [x] [Professor Frisby's Mostly Adequate Guide to Functional Programming](https://mostly-adequate.gitbooks.io/mostly-adequate-guide/)
- [x] [Learn You a Haskell for Great Good!](http://learnyouahaskell.com/)
- [ ] [Real World Haskell](http://book.realworldhaskell.org/read/)
- [x] 函数式编程思维
- [x] Java 8 Lambdas
- [ ] [Category Theory for Programmers](https://github.com/hmemcpy/milewski-ctfp-pdf/)
- [ ] [Jargon from the functional programming world in simple terms!](https://github.com/hemanth/functional-programming-jargon)
- [ ] [Awesome FP JS](https://github.com/stoeffel/awesome-fp-js)
- [ ] [fantasy-land: Specification for interoperability of common algebraic structures in JavaScript](https://github.com/fantasyland/fantasy-land)

 🎥Videos
- [x] [Hey Underscore, You're Doing It Wrong!](https://www.youtube.com/watch?v=m3svKOdZijA&app=desktop)
- [x] [Brian Beckman: Don't fear the Monad](https://youtu.be/ZhuHCtR3xq8) 需要二刷
- [x] [Functional programming in JavaScript](https://www.youtube.com/playlist?list=PL0zVEGEvSaeEd9hlmCXrk5yUyqUag-n84)
- [x] [Professor Frisby Introduces Composable Functional JavaScript](https://egghead.io/courses/professor-frisby-introduces-composable-functional-javascript)
- [x] [Functional programming patterns for the non-mathematician](https://www.youtube.com/watch?v=AvgwKjTPMmM)
- [x] [JavaScript Programmers Should Learn Algebraic Data Types](https://www.youtube.com/watch?v=B0VoyujJWIE)
- [x] [Transducers Explained | JavaScript - YouTube](https://www.youtube.com/watch?v=SJjOp0X_MVA)

📝Articles
- [x] [OO vs FP](http://blog.cleancoder.com/uncle-bob/2014/11/24/FPvsOO.html)👍
- [x] [Thinkin in Ramda](http://randycoulman.com/blog/categories/thinking-in-ramda/)
- [x] [jargon](https://github.com/hemanth/functional-programming-jargon)
- [x] [Dipping a toe into functional JS with lodash/fp](https://simonsmith.io/dipping-a-toe-into-functional-js-with-lodash-fp/)

## Rx
📚Books
- [ ] Reactive Programming with RxJS
- [ ] RxJS in Action

🎥Videos
- [x] [RxJS Beyond the Basics: Creating Observables from scratch](https://egghead.io/courses/rxjs-beyond-the-basics-creating-observables-from-scratch)👍
- [ ] [RxJS Beyond the Basics: Operators in Depth](https://egghead.io/courses/rxjs-beyond-the-basics-operators-in-depth)

**Comment by futantan** [comment]
Moved to https://github.com/futantan/futantan.github.io/wiki/Functional-Programming
